config/routes.rb
Rails.application.routes.draw do
  resources :friendships
  resources :fights
  resources :scores
  resources :dashboard
  devise_for :users
  root to: "home#index"
  
  get 'users/index'
  get 'users/show'

  get 'fights/new'
  get 'main_pages/login'
  get 'dashboard/index'
  get 'main_pages/home'
  get 'main_pages/score'
  get 'main_pages/results'
  post 'scores/new'

end

app/models/fight.rb
class Fight < ActiveRecord::Base
	belongs_to :user
	has_many :scores
end

app/models/friendship.rb
class Friendship < ActiveRecord::Base
	belongs_to :user
	belongs_to :friend, :class_name => "User"
end

app/models/score.rb
class Score < ActiveRecord::Base
	belongs_to :fight
	belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  has_many :fights
  has_many :scores
  has_many :friendships
  has_many :friends, :through => :friendships
  has_many :inverse_friendships, :class_name => "Friendship", :foreign_key => "friend_id"
  has_many :inverse_friends, :through => :inverse_friendships, :source => :user
  
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  before_filter :authenticate_user!
  def index
  	@score = Score.find_by fight_id: 1, user_id: current_user.id
    # @users = User.all
    @user = current_user
    @emails = @user.friends.select { |friend| friend.scores.any? { |score| score.fight_id == 1 } }.collect { |friend| friend.email }
    # @friendscore = @friends.collect { |friend| friend.scores.select { |score| score.fight_id == 1 } }
    @output = @emails.collect do |email|
    	user_id = User.find_by(email: email).id
    	subarr = []
    	subarr.push email
    	subarr.push []
    	user = Score.find_by(user_id: user_id)
    	subarr[1].push user.r1_f1
    	subarr[1].push user.r1_f2
    	subarr[1].push user.r2_f1
    	subarr[1].push user.r2_f2
    	subarr[1].push user.r3_f1
    	subarr[1].push user.r3_f2
    	subarr
    end

  end

  def show
    @user = current_user
  	
  end
end

app/controllers/fights_controller.rb
class FightsController < ApplicationController
  def new
  end

  def create
  	
  end
end

app/controllers/friendships_controller.rb
class FriendshipsController < ApplicationController
  before_action :set_friendship, only: [:show, :edit, :update, :destroy]

  # GET /friendships
  # GET /friendships.json
  def index
    @friendships = Friendship.all
  end

  # GET /friendships/1
  # GET /friendships/1.json
  def show
  end

  # GET /friendships/new
  def new
    @friendship = Friendship.new
  end

  # GET /friendships/1/edit
  def edit
  end

  # POST /friendships
  # POST /friendships.json
  def create
    @friendship = current_user.friendships.build(:friend_id => params[:friend_id])
    if @friendship.save
      flash[:notice] = "Added friend"
      redirect_to '/users/show'
    else
      flash[:error] = "Unable to add friend."
      redirect_to root_url
    end

  
  end

  # PATCH/PUT /friendships/1
  # PATCH/PUT /friendships/1.json
  def update
    respond_to do |format|
      if @friendship.update(friendship_params)
        format.html { redirect_to @friendship, notice: 'Friendship was successfully updated.' }
        format.json { render :show, status: :ok, location: @friendship }
      else
        format.html { render :edit }
        format.json { render json: @friendship.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /friendships/1
  # DELETE /friendships/1.json
  def destroy
    @friendship = current_user.friendships.find(params[:id])
    @friendship.destroy
    flash[:notice] = "Removed friendship."
    redirect_to '/users/show'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_friendship
      @friendship = Friendship.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def friendship_params
      params.require(:friendship).permit(:user_id, :friend_id)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    if user_signed_in?
      redirect_to :controller =>'dashboard', :action => 'index'
    end
  end
end

app/controllers/main_pages_controller.rb
class MainPagesController < ApplicationController
  def login
  end

  def home
  end

  def score
  	if user_signed_in?
  		@fight = current_user.fights.new
  		@fight.save
  	end
  end

  def results
  end

  # def new
  # 	if user_signed_in?
  # 		@fight = current_user.fights.new
  # 	end
  # end

  def create
  	@fight = current_user.fights.new(fights_params)
  	@fight.save
  end

  def fights_params
  	params.require(:fight).permit(:fighterone, :fightertwo)
  end
end

app/controllers/scores_controller.rb
class ScoresController < ApplicationController
  before_action :set_score, only: [:show, :edit, :update, :destroy]

  # GET /scores
  # GET /scores.json
  def index
    @scores = Score.all
  end

  # GET /scores/1
  # GET /scores/1.json
  def show
  end

  # GET /scores/new
  def new
    @score = Score.new
    @score.fight_id = params[:fight_id].to_i
  end

  # GET /scores/1/edit
  def edit
  end

  # POST /scores
  # POST /scores.json
  def create
    @score = Score.new(score_params)
    @score.user_id = current_user.id
    respond_to do |format|
      if @score.save
        format.html { redirect_to :controller => 'dashboard', :action => 'index' }
        format.json { render :show, status: :created, location: @score }
      else
        format.html { render :new }
        format.json { render json: @score.errors, status: :unprocessable_entity }
      end
    end

  end

  # PATCH/PUT /scores/1
  # PATCH/PUT /scores/1.json
  def update
    respond_to do |format|
      if @score.update(score_params)
        format.html { redirect_to @score, notice: 'Score was successfully updated.' }
        format.json { render :show, status: :ok, location: @score }
      else
        format.html { render :edit }
        format.json { render json: @score.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /scores/1
  # DELETE /scores/1.json
  def destroy
    @score.destroy
    respond_to do |format|
      format.html { redirect_to scores_url, notice: 'Score was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_score
      @score = Score.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def score_params
      params.require(:score).permit(:r1_f1, :r2_f1, :r3_f1, :r1_f2, :r2_f2, :r3_f2, :fight_id)
    end


end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    @users = User.all
  end
  
  def show
    @user = current_user
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/fights_helper.rb
module FightsHelper
end

app/helpers/friendships_helper.rb
module FriendshipsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/main_pages_helper.rb
module MainPagesHelper
end

app/helpers/scores_helper.rb
module ScoresHelper
end

app/views/dashboard/index.html.erb
<!DOCTYPE html>
<html>
<head>
	<title>Events to Score</title>
	<link href='http://fonts.googleapis.com/css?family=Julee' rel='stylesheet' type='text/css'>
</head>
<body>

<div id="friend_links"><h3 id="h3"><center><a href="users/index">Find Your Friends!</a><span class="dots">..</span>|<span class="dots">..</span><a href="users/show">List of Your Friends</a></center></h3></div>

  <h1 id="eve">Events to score</h1>
  
  <div id="evecont">
    <center>UFC 176</center>
    <br>
    <br>
    <center>

    <%= form_tag('/scores/new', method: 'post') do %>
      	<%= hidden_field_tag :fight_id, 1 %>
      	<%= hidden_field_tag :authenticity_token, form_authenticity_token %>
      	<%= submit_tag("Score GSP vs. Silva", class: "myButton", id: "eventbutton") %>
    <% end %>
  </center>
</div>

<% if @score %>
<h1 id="fes">Friends' scored events</h1>
<h1 id="mes">My scored events</h1>
<div id="myscores">
  <div class="score">
  <center>GSP vs. Anderson Silva</center>
  <br>
    <table id="tab">
      <tr>
        <th>Fighter</th>
        <th>Round 1</th> 
        <th>Round 2</th>
        <th>Round 3</th>
      </tr>
      	<tr>
          <td>GSP</td>
          <td><%= @score.r1_f1 %></td>
      	  <td><%= @score.r2_f1 %></td>
      	  <td><%= @score.r3_f1 %></td>
        </tr>
        <tr>
          <td>Silva</td>
      	  <td><%= @score.r1_f2 %></td>
      	  <td><%= @score.r2_f2 %></td>
      	  <td><%= @score.r3_f2 %></td>
        </tr>
    </table>
  
  </div>
</div>

  </center>

<div id="friendscores">
  <% count = 0 %>
  <% if @output[count] != nil %>
    <% while (@output.length)/2 >= count %>
      <div class="score">
      <center>GSP vs. Anderson Silva</center> 
      <br>
      <span>Friend: <%= @output[count][0] %></span>
      <br>
      <br>
          <table class="tab">
            <tr>
              <th>Fighter</th>
              <th>Round 1</th> 
              <th>Round 2</th>
              <th>Round 3</th>
            </tr>
            <tr>
              <td>GSP</td>
              <td><%= @output[count][1][0] %></td>
              <td><%= @output[count][1][1] %></td>
              <td><%= @output[count][1][2] %></td>
            </tr>
            <tr>
              <td>Silva</td>
              <td><%= @output[count][1][3] %></td>
              <td><%= @output[count][1][4] %></td>
              <td><%= @output[count][1][5] %></td>
            </tr>
          </table>
        </div>
        <br>
        <br>
      <% count = count + 1 %>
    <% end %>
    </div>
  <% end %>
<% end %>

</body>

app/views/dashboard/show.html.erb
<h1>hello world</h1>

<%= current_user.fights %>

app/views/fights/new.html.erb
<h1>Fights#new</h1>
<p>Find me in app/views/fights/new.html.erb</p>

app/views/friendships/_form.html.erb
<%= form_for(@friendship) do |f| %>
  <% if @friendship.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@friendship.errors.count, "error") %> prohibited this friendship from being saved:</h2>

      <ul>
      <% @friendship.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.number_field :user_id %>
  </div>
  <div class="field">
    <%= f.label :friend_id %><br>
    <%= f.number_field :friend_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/friendships/edit.html.erb
<h1>Editing friendship</h1>

<%= render 'form' %>

<%= link_to 'Show', @friendship %> |
<%= link_to 'Back', friendships_path %>

app/views/friendships/index.html.erb
<h1>Listing friendships</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Friend</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @friendships.each do |friendship| %>
      <tr>
        <td><%= friendship.user_id %></td>
        <td><%= friendship.friend_id %></td>
        <td><%= link_to 'Show', friendship %></td>
        <td><%= link_to 'Edit', edit_friendship_path(friendship) %></td>
        <td><%= link_to 'Destroy', friendship, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Friendship', new_friendship_path %>

app/views/friendships/new.html.erb
<h1>New friendship</h1>

<%= render 'form' %>

<%= link_to 'Back', friendships_path %>

app/views/friendships/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @friendship.user_id %>
</p>

<p>
  <strong>Friend:</strong>
  <%= @friendship.friend_id %>
</p>

<%= link_to 'Edit', edit_friendship_path(@friendship) %> |
<%= link_to 'Back', friendships_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>YouDaJudge</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<div id="user_nav">
  <% if user_signed_in? %>	
    Signed in as <%= current_user.email %>. Not you?  
    <%= link_to "   Sign out", destroy_user_session_path, :method => :delete %>
   <% else %>
     <%= link_to "Sign up", new_user_registration_path %> or <%= link_to "Sign in", new_user_session_path %>
   <% end %>
</div>
<% flash.each do |name,msg| %>
<%= content_tag :div, msg, :id => "flash_#{name}" %>
<% end %>

<%= yield %>

</body>
</html>

app/views/main_pages/home.html.erb
<h1>MainPages#home</h1>
<p>Find me in app/views/main_pages/home.html.erb</p>

app/views/main_pages/login.html.erb
<h1>MainPages#login</h1>
<p>Find me in app/views/main_pages/login.html.erb</p>

app/views/main_pages/results.html.erb
<h1>MainPages#results</h1>
<p>Find me in app/views/main_pages/results.html.erb</p>

app/views/main_pages/score.html.erb
<div class="row">

  <div class="span6 offset3">
  <% if user_signed_in? %>
    <%= form_for @fight do |f| %>

      <%= f.label "fighter one" %>
      <%= f.number_field :fighterone %>

      <%= f.label "Fighter two" %>
      <%= f.number_field :fightertwo %>

      <%= f.submit "Score the fight", class: "btn btn-large btn-primary" %>
    <% end %>
  <% end %>

  </div>
</div>

app/views/scores/_form.html.erb
<%= form_for(@score) do |f| %>
  <% if @score.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@score.errors.count, "error") %> prohibited this score from being saved:</h2>

      <ul>
      <% @score.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<div id="scorecardcontainer1">
<center><h2>Round 1</h2></center>
       <div><%=image_tag 'silva.jpg', id: "fighter2" %></div>
       <div><%= image_tag 'gsp.jpg', id: "fighter1" %></div><br>
    
       <div class="columnleft">
        <%= f.radio_button :r1_f1, '10' %> 
        <%= label :ten, '10' %><br><br>
        <%= f.radio_button :r1_f1, '9' %>
        <%= label :nine, '9' %><br><br>
        <%= f.radio_button :r1_f1, '8' %>
        <%= label :eight, '8' %>
      </div>

      <div class="columnright">
        <%= f.radio_button :r1_f2, '10' %> 
        <%= label :ten, '10' %><br><br>
        <%= f.radio_button :r1_f2, '9' %>
        <%= label :nine, '9' %><br><br>
        <%= f.radio_button :r1_f2, '8' %>
        <%= label :eight, '8' %>
       </div>
     <!--  <center><div id="submit"><input type="submit" value="Judge" class="myButton"></center> -->
</div>
  <!-- First Round Scorecard -->
  
<div id="scorecardcontainer2">
<center><h2>Round 2</h2></center>
       <div><%=image_tag 'silva.jpg', id: "fighter2" %></div>
       <div><%= image_tag 'gsp.jpg', id: "fighter1" %></div><br>
    
       <div class="columnleft">
        <%= f.radio_button :r2_f1, '10' %> 
        <%= label :ten, '10' %><br><br>
        <%= f.radio_button :r2_f1, '9' %>
        <%= label :nine, '9' %><br><br>
        <%= f.radio_button :r2_f1, '8' %>
        <%= label :eight, '8' %>
      </div>

      <div class="columnright">
        <%= f.radio_button :r2_f2, '10' %> 
        <%= label :ten, '10' %><br><br>
        <%= f.radio_button :r2_f2, '9' %>
        <%= label :nine, '9' %><br><br>
        <%= f.radio_button :r2_f2, '8' %>
        <%= label :eight, '8' %>
       </div>
     <!--  <center><div id="submit"><input type="submit" value="Judge" class="myButton"></center> -->
</div>
 
<div id="scorecardcontainer3">
<center><h2>Round 3</h2></center>
       <div><%=image_tag 'silva.jpg', id: "fighter2" %></div>
       <div><%= image_tag 'gsp.jpg', id: "fighter1" %></div><br>
    
       <div class="columnleft">
        <%= f.radio_button :r3_f1, '10' %> 
        <%= label :ten, '10' %><br><br>
        <%= f.radio_button :r3_f1, '9' %>
        <%= label :nine, '9' %><br><br>
        <%= f.radio_button :r3_f1, '8', class: "chb" %>
        <%= label :eight, '8' %>
      </div>

      <div class="columnright">
        <%= f.radio_button :r3_f2, '10' %> 
        <%= label :ten, '10' %><br><br>
        <%= f.radio_button :r3_f2, '9' %>
        <%= label :nine, '9' %><br><br>
        <%= f.radio_button :r3_f2, '8' %>
        <%= label :eight, '8' %>
       </div>
     <!--  <center><div id="submit"><input type="submit" value="Judge" class="myButton"></center> -->
</div>

  <%= f.hidden_field :fight_id %>
 <center> <%= f.submit "Score the bout", class: "myButton" %></center>

  
<% end %>

app/views/scores/edit.html.erb
<h1>Editing score</h1>

<%= render 'form' %>

<%= link_to 'Show', @score %> |
<%= link_to 'Back', scores_path %>

app/views/scores/index.html.erb
<h1>Listing scores</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @scores.each do |score| %>
      <tr>
        <td><%= link_to 'Show', score %></td>
        <td><%= link_to 'Edit', edit_score_path(score) %></td>
        <td><%= link_to 'Destroy', score, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Score', new_score_path %>

app/views/scores/new.html.erb
<head>
	<title>Score the fight!</title>
	<link href='http://fonts.googleapis.com/css?family=Julee' rel='stylesheet' type='text/css'>
</head>

<h1>Score the fight</h1>

<%= render 'form' %>

<%= link_to 'Back', scores_path, id: "back" %>

app/views/scores/show.html.erb
<p id="notice"><%= notice %></p>
<%= @score.fight_id %>

<%= link_to 'Edit', edit_score_path(@score) %> |
<%= link_to 'Back', scores_path %>
<%= @score.inspect %>

app/views/users/index.html.erb
<ul class="nav">
	<li><a href="/">Home</a></li>
	<li><a href="/users/show">List my Friends</a></li>
</ul>
<h1>Users List</h1>


<div id="users">
	<% for user in @users %>
	  <div class="user">
	    <p>
	      <strong><%=h user.email %></strong>
	      <%= link_to "Add Friend", friendships_path(:friend_id => user), :method => :post, :class => "addfriend" %>
	      <div class="clear"></div>
	    </p>
	  </div>
	<% end %>
</div>

app/views/users/show.html.erb
<ul class="nav">
	<li><a href="/">Home</a></li>
	<li><a href="/users/index">Find Your Friends!</a></li>
</ul>

<h2>My Friends</h2>

<ul>
  <% for friendship in @user.friendships %>
  <div class="friend">
    <li>
      <%=h friendship.friend.email %><span>
      (<%= link_to "remove", friendship, :method => :delete, :class => "remove" %>)</span>
    </li>
</div>
  <% end %>
</ul>


<h2>Friended by Users</h2>
<ul>
  <% for user in @user.inverse_friends %>
  <div class="others">
    <li><%=h user.email %></li>
</div>
  <% end %>
</ul>